### ISSUE TITLE
Up next (bug)

### ISSUE THREAD

**Issue by CassieColby** [HighlanderRobotics/scouting_dashboard_app#102]

**Comment by CassieColby** [comment]
![Image](https://github.com/HighlanderRobotics/scouting_dashboard_app/assets/70112547/e5a49dfa-6d38-4303-8bb8-2ee6dffa53f3)


Don't worry abt why there is only one match (team run scrimmage). 

This is 2024 Regal Eagle Rampage

**Comment by MangoSwirl** [comment]
Fixed by #94 and #98
