### ISSUE TITLE
Error page for match schedule when tournament doesn't exist

### ISSUE THREAD

**Issue by MangoSwirl** [HighlanderRobotics/scouting_dashboard_app#103]
I want this so when i delete 2023 tournaments people aren't confused.  I can make a custom error message as well -cassie.

**Comment by CassieColby** [comment]
I already have an error message. Is there something else you are needing me to do?

**Comment by CassieColby** [comment]
<img width="937" alt="image" src="https://github.com/HighlanderRobotics/scouting_dashboard_app/assets/70112547/ca2d08df-d5e7-45a6-b628-f245f928288e">
is this what it should look like?

**Comment by MangoSwirl** [comment]
> <img width="937" alt="image" src="https://github.com/HighlanderRobotics/scouting_dashboard_app/assets/70112547/ca2d08df-d5e7-45a6-b628-f245f928288e">
> 
> is this what it should look like?

Did you mean to comment that here?

**Comment by MangoSwirl** [comment]
And yes, that is correct. Click on "Learn" for the new pages.

**Comment by CassieColby** [comment]
oops wrong that in the wrong issue lol
