### ISSUE TITLE
EPA Box on Team Look Up

### ISSUE THREAD

**Issue by CassieColby** [HighlanderRobotics/scouting_dashboard_app#13]
Wait until me and sophie have added it, prob by 9/7/23

Hopefully Olivia can work on it,

**Comment by MangoSwirl** [comment]
What will the API look like? Will it have a details page? What category should it be under?

**Comment by CassieColby** [comment]
So basically its going to be a version of epa calculated with our data. It can just be a box (no details) on the team look up page. I think we should rename the statbotics section to EPA and have two stats under -> Statbotics EPA and our EPA. The win rate can be moved next to driver ability or removed from the page
