### ISSUE TITLE
Flags Icon

### ISSUE THREAD

**Issue by CassieColby** [HighlanderRobotics/scouting_dashboard_app#14]
0: bad
1: medium bad
2: neutral
3: medium good
4: good

everywhere w/ teams under the name "flag"

**Comment by MangoSwirl** [comment]
Can you give more details on the API? Is this replacing where a team number would normally be sent? For which endpoints? And is the flag representing overall abilities compared to other teams at the tournament or is it change over time? If it's about a team's change trend, then the enum should probably have more specific naming, i.e., slightly improving, greatly improving, no change.

**Comment by CassieColby** [comment]
So how I was imaging it working is where there is a field "team" : 8033 (ex in category metrics sends "team" : #, "result : {}) there would be a third field that said "flag" and would give an enum. Alternatively where it says team we could just set it equal to {"teamNumber" : #, "flag" : enum}, up to you.
As discussed in person, the flag is talking about trends in an induvial team, and yes I will 100% change the names before publishing.

**Comment by CassieColby** [comment]
Updated enums:

0: greatly worsening
1: slightly worsening
2: no change
3: slightly improving
4: greatly improving

**Comment by MangoSwirl** [comment]
Replaced by #15
