### ISSUE TITLE
Flags (team lookup page)

### ISSUE THREAD

**Issue by CassieColby** [HighlanderRobotics/scouting_dashboard_app#15]
- [ ] Make settings page where they can select which thing they want to see
- [ ] Make icons, and send the settings thing through the endpoint under: "flagType"

Options:
"trend" = trend arrows
"pentalties" =  0: none, 1 : yellow, 2: red (spelled wrong still, fix sunday)
"mainRole" = 0: offense 1 : defense 2: feeder 3 immobile 
"ranking" = blue alliance ranking
"anyCategoryMetric" = the result (avg)

I'm not sure what other ones we were thinking abt, lmk if you remember. Also lmk if its easier for all of the enum output options to be unique (instead of multiple from 0-3 have one big chart form 0-n)

**Comment by MangoSwirl** [comment]
I think having enums specific to each flag type would make the most sense. I think we also talked about being able to make any category metric into a flag. Maybe for these we could have prefix like `metric-x`. How much of this is implemented on your end?

**Comment by CassieColby** [comment]
I think that the metric-x thing should only be for picklists. Rn I have it implemented for the team look up page (some of the inputs i sent originally are missing). I think it would be good for Sophie to augment it for picklists on thursday.
