### ISSUE TITLE
Update scouter shift page

### ISSUE THREAD

**Issue by CassieColby** [HighlanderRobotics/scouting_dashboard_app#44]
Right now we have it so that each team in a given shift can only have one scouter, allow them to add more scouters for a given team. Don't make it so that all the teams in that shift require the same amount because some teams might want irregular amounts of scouters per team (example bc idk if i'm being clear: team 1 has 2 scouters, team 2 has 1 scouter, etc)

**Comment by MangoSwirl** [comment]
There will also need to be changes related to making scouter schedules unique to a team/tournament. Previously there was one scouter schedule stored for the entire system. We will also need to consider our "set up to scout" flow which will walk users through choosing a tournament, who they'll share their data with, and creating a scouter shift.

**Comment by CassieColby** [comment]
Yes agreed, if possible update the page itself soon to accommodate this. When we are working on scouting lead specific features we can talk about where it goes/where they are navigated to.

**Comment by MangoSwirl** [comment]
> When we are working on scouting lead specific features we can talk about where it goes/where they are navigated to.
Is editing the scouter schedule not a scouting lead specific feature?

**Comment by CassieColby** [comment]
Yup it is, sorry that wasn't worded well. What I meant is: work on updating the scouter schedule page now, and later on we can talk about where it goes/the flow later on. The endpoints are ready btw

**Comment by MangoSwirl** [comment]
If we don't have a way to specify which tournament the schedule is for then
how will it know what to send?

**Comment by CassieColby** [comment]
We do want to have a way to select the tournament, that's probably something you should add to the scouter schedule page, unless you have a different place in mind.
