### ISSUE TITLE
Settings Page (frontend dashboard)

### ISSUE THREAD

**Issue by CassieColby** [HighlanderRobotics/scouting_dashboard_app#48]
- [x] Team source
- [x] Tournament source
- [x] Delete user
- [x] Tournament they're at
- [x] Promote users

**Comment by CassieColby** [comment]
- Team source
- Tournament source
- delete user (wont allow if only scouting lead on team)
- FOR SCOUTING LEADS ONLY: upgrade other users to scouting lead from their team

**Comment by MangoSwirl** [comment]
And also tournament they're at?

**Comment by MangoSwirl** [comment]
And can I send GET requests to team source and tournament source to get what's currently selected?

**Comment by CassieColby** [comment]
Yes, let me make those real quick

**Comment by CassieColby** [comment]
No there wont be, i think it would be weird bc we wont know who the "highest" level person is

**Comment by MangoSwirl** [comment]
Do we want to add a third role for that "highest person"?

**Comment by CassieColby** [comment]
In my opinion no, I can elaborate on why in person if your curious
