### ISSUE TITLE
Category metrics

### ISSUE THREAD

**Issue by CassieColby** [HighlanderRobotics/scouting_dashboard_app#56]

**Comment by CassieColby** [comment]
totalpoints
driverability
teleoppoints
autopoints
pickups
ampscores
speakerscores
trapscores
feeds
drops

GET /v1/analysis/category/team/:team

**Comment by MangoSwirl** [comment]
I have all of these in. We'll need to decide on how to categorize them at some point. Since there isn't an endpoint included for details pages, I'm assuming that will fall into the scope of another issue.

**Comment by CassieColby** [comment]
Thats correct, lets discuss today. Great work!
