### ISSUE TITLE
Alliance

### ISSUE THREAD

**Issue by CassieColby** [HighlanderRobotics/scouting_dashboard_app#62]

**Comment by CassieColby** [comment]
GET /v1/analysis/alliance

current format:
{
            totalPoints : teamOnePoints.average + teamTwoPoints.average + teamThreePoints.average,
            teams :[{ team : team1, role : teamOneMainRole, averagePoints : teamOnePoints.average, paths : teamOneAutoPaths},
                {team : team2, role : teamTwoMainRole, averagePoints : teamTwoPoints.average, paths : teamTwoAutoPaths},
                {team : team3, role : teamThreeMainRole, averagePoints : teamThreePoints.average, paths : teamThreeAutoPaths}
            ],
            speakerScores : teamOneSpeakerScores.average + teamTwoSpeakerScores.average + teamThreeSpeakerScores.average,
            ampscores : teamOneAmpScores.average + teamTwoAmpScores.average + teamThreeAmpScores.average
        }

**Comment by MangoSwirl** [comment]
Pending [requested API changes](https://frc8033.slack.com/archives/D046R3K6FM1/p1706855505912799).
