### ISSUE TITLE
Newly upgraded scouting leads can't view scout report

### ISSUE THREAD

**Issue by CassieColby** [HighlanderRobotics/scouting_dashboard_app#89]

**Comment by CassieColby** [comment]
One way to reproduce:
- get upgraded to scouting lead while in match schedule
- refresh match schedule
- go to settings
- refresh match schedule
- still won't let me view scoutreports
If I close and reopen everything works

**Comment by MangoSwirl** [comment]
You just have to go to a different page in order for it to refresh. To make it automatically refresh we would need to implement SSE.

**Comment by CassieColby** [comment]
Got it, settings doesn't count as a different page tho?

**Comment by MangoSwirl** [comment]
It's gotta be a page with the menu icon, not a back icon. So it has to be a new match schedule page, not going back to the old one.

**Comment by CassieColby** [comment]
Ah ok

**Comment by MangoSwirl** [comment]
Will be fixed by #94

**Comment by MangoSwirl** [comment]
Fixed by #94
