### ISSUE TITLE
rounding

### ISSUE THREAD

**Issue by CassieColby** [HighlanderRobotics/scouting_dashboard_app#96]
- [ ] Alliance
- [x] Match prediction
- [ ] picklists (?)
- [ ] Team look up

**Comment by MangoSwirl** [comment]
What pages?

**Comment by CassieColby** [comment]
Alliance
Match prediction
picklists (?)
Team look up

**Comment by MangoSwirl** [comment]
@CassieColby I fixed the issue we found in Alex's text but can't find the other instances you sent.

**Comment by CassieColby** [comment]
Vaughn shows it to me on alliance and match prediction today.

**Comment by CassieColby** [comment]
Vaughn says "if you match predict anything it has a million decimal points". If you still can't find it ill send pics later but hes in the middle of driving and my phones about to die

**Comment by MangoSwirl** [comment]
Yeah it would be great if we could get specific screenshots.

**Comment by MangoSwirl** [comment]
Cannot reproduce issues with alliance, picklist, or team lookup pages.
